Chore/config prettier con eslint
freecodecamp-venezuela/ecommerce-coffee pull request #31
Opened 2021-03-19 04:41 UTC by mcljs

Configuración de Prettier con Eslint

2021-03-20 19:45 UTC, darthzyklus commented
@mcljs please resolve the conflicts to continue

2021-03-20 19:46 UTC, darthzyklus requested changes
the PR needs to resolve the conflicts to continue and merge into develop.

2021-03-21 00:56 UTC, darthzyklus approved these changes

2021-03-21 01:07 UTC, Hmerin commented
@mcljs I think the `.vscode` directory shouldn’t be committed or just left the following lines:

```

2021-03-21 01:20 UTC, Hmerin reviewed
@mcljs Please edit the description providing an example of how to test this config or how to trigger the `codeActionsOnSave` I haven’t lucky editing some files expecting this config to make the lint automatically

2021-03-21 01:20 UTC, Hmerin commented on .vscode/settings.json
> +  "window.zoomLevel": 5,
This line modifies the other ppl editors, please left the eslint/prettier related configs

2021-03-21 01:41 UTC, mcljs commented
The configuration and issues with this branch were resolved in PR # 32 . Details which were:

problems in the fontsize .vscode
conflict issues with the develop branch

2021-03-21 01:44 UTC, closed without merging

2021-03-21 01:45 UTC, Hmerin commented
PR close in favor of #32